services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/src
    depends_on:
      - valkey
    environment:
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379

  valkey:
    image: valkey/valkey:8.0-alpine
    volumes:
      - valkey-data:/data
    ports:
      - "6379:6379"

volumes:
  valkey-data:
