services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/src
    depends_on:
      - valkey
      - db
    environment:
      - VALKEY_HOST=valkey
      - VALKEY_PORT=6379

  valkey:
    image: valkey/valkey:8.0-alpine
    volumes:
      - valkey-data:/data
    ports:
      - "6379:6379"

  db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  valkey-data:
  postgres-data:
