name: Code quality

on:
  pull_request:

concurrency:
  group: code-quality-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  frontend:
    name: Frontend lint, format and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache-dependency-path: frontend
          node-version: '22.12.0'
          cache: 'npm'

      - shell: bash
        run: |
          cd frontend
          npm ci
          npm run format
          npm run lint
          npm run test
  backend:
    name: Backend lint, format and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache-dependency-path: backend
          node-version: '22.12.0'
          cache: 'npm'

      - shell: bash
        run: |
          cd backend
          npm ci
          npm run format
          npm run lint
          npm run test
